name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: yarn lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint